builds:
  - binary: seed
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # This naming format is important for Homebrew
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Windows users expect zip files
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# Generate a CHANGELOG from git commits
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

# SHA256 checksums are crucial for Homebrew
checksum:
  name_template: "checksums.txt"
